# Generated by Django 5.2.7 on 2025-10-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooldata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
